Mod-3/Week-1/lecture-1-intro-to-rails/ending-code/tourist-app/config/routes.rb
Rails.application.routes.draw do
  resources :tours
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

Mod-3/Week-1/lecture-1-intro-to-rails/ending-code/tourist-app/app/models/tour.rb
class Tour < ApplicationRecord
    has_many :tourists
end

Mod-3/Week-1/lecture-1-intro-to-rails/ending-code/tourist-app/app/models/tourist.rb
class Tourist < ApplicationRecord
  belongs_to :tour
end

Mod-3/Week-1/lecture-1-intro-to-rails/ending-code/tourist-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Mod-3/Week-1/lecture-1-intro-to-rails/ending-code/tourist-app/app/controllers/tourists_controller.rb
class TouristsController < ApplicationController
end

Mod-3/Week-1/lecture-1-intro-to-rails/ending-code/tourist-app/app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :set_tour, only: [:show, :edit, :update, :destroy]

  # GET /tours
  # GET /tours.json

  def index
    @tours = Tour.all
  end

  # GET /tours/1
  # GET /tours/1.json
  def show
  end

  # GET /tours/new
  def new
    @tour = Tour.new
  end

  # GET /tours/1/edit
  def edit
  end

  # POST /tours
  # POST /tours.json
  def create
    @tour = Tour.new(tour_params)
    if @tour.save
      redirect_to @tour, notice: 'Tour was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tours/1
  # PATCH/PUT /tours/1.json
  def update
      if @tour.update(tour_params)
        redirect_to @tour, notice: 'Tour was successfully updated.'
      else
        render :edit
      end
  end

  # DELETE /tours/1
  # DELETE /tours/1.json
  def destroy
    @tour.destroy
    redirect_to tours_url, notice: 'Tour was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour
      @tour = Tour.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tour_params
      params.require(:tour).permit(:name, :location, :activities, :cost, :start_time, :end_time, :tour_date, :full)
    end
end

Mod-3/Week-1/lecture-1-intro-to-rails/ending-code/tourist-app/app/helpers/tourists_helper.rb
module TouristsHelper
end

Mod-3/Week-1/lecture-1-intro-to-rails/ending-code/tourist-app/app/helpers/tours_helper.rb
module ToursHelper
end

Mod-3/Week-1/lecture-1-intro-to-rails/ending-code/tourist-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TouristApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Mod-3/Week-1/lecture-1-intro-to-rails/ending-code/tourist-app/app/views/tours/_form.html.erb
<%= form_with(model: tour, local: true) do |form| %>
  <% if tour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tour.errors.count, "error") %> prohibited this tour from being saved:</h2>

      <ul>
        <% tour.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :activities %>
    <%= form.text_field :activities %>
  </div>

  <div class="field">
    <%= form.label :cost %>
    <%= form.text_field :cost %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.time_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.time_select :end_time %>
  </div>

  <div class="field">
    <%= form.label :tour_date %>
    <%= form.date_select :tour_date %>
  </div>

  <div class="field">
    <%= form.label :full %>
    <%= form.check_box :full %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Mod-3/Week-1/lecture-1-intro-to-rails/ending-code/tourist-app/app/views/tours/edit.html.erb
<h1>Editing Tour</h1>

<%= render 'form', tour: @tour %>

<%= link_to 'Show', @tour %> |
<%= link_to 'Back', tours_path %>

Mod-3/Week-1/lecture-1-intro-to-rails/ending-code/tourist-app/app/views/tours/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tours</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Activities</th>
      <th>Cost</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Tour date</th>
      <th>Full</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tours.each do |tour| %>
      <tr>
        <td><%= tour.name %></td>
        <td><%= tour.location %></td>
        <td><%= tour.activities %></td>
        <td><%= tour.cost %></td>
        <td><%= tour.start_time %></td>
        <td><%= tour.end_time %></td>
        <td><%= tour.tour_date %></td>
        <td><%= tour.full %></td>
        <td><%= link_to 'Show', tour %></td>
        <td><%= link_to 'Edit', edit_tour_path(tour) %></td>
        <td><%= link_to 'Destroy', tour, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tour', new_tour_path %>

Mod-3/Week-1/lecture-1-intro-to-rails/ending-code/tourist-app/app/views/tours/new.html.erb
<h1>New Tour</h1>

<%= render 'form', tour: @tour %>

<%= link_to 'Back', tours_path %>

Mod-3/Week-1/lecture-1-intro-to-rails/ending-code/tourist-app/app/views/tours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tour.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @tour.location %>
</p>

<p>
  <strong>Activities:</strong>
  <%= @tour.activities %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @tour.cost %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @tour.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @tour.end_time %>
</p>

<p>
  <strong>Tour date:</strong>
  <%= @tour.tour_date %>
</p>

<p>
  <strong>Full:</strong>
  <%= @tour.full %>
</p>

<p>
  <strong>Tourists:</strong>
  <% @tour.tourists.each do |tourist| %>
    <p><%= tourist.name %></p>
  <% end %>
</p>



<%= link_to 'Edit', edit_tour_path(@tour) %> |
<%= link_to 'Back', tours_path %>