Mod-3/Week-1/lecture-3-rails-crud/ending-code/study-group-sushi/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :sushis
#  #index
#   get '/sushis', to: "sushis#index"

# #new
#   get '/sushis/new', to: "sushis#new", as: "new_sushis"  

# #create

#  post '/sushis', to: "sushis#create"
 
#  #show
#  get '/sushis/:id', to: "sushis#show", as: "sushi"

#  # edit
#  get '/sushis/:id/edit', to: "sushis#edit", as: "edit_sushi"

#  #update
#  patch '/sushis/:id', to: "sushis#update"

#  # delete

#  delete '/sushis/:id', to: "sushis#destroy"

  get '/', to: "sushis#home"
  get '/:anything', to: "application#wrong_page"
end

Mod-3/Week-1/lecture-3-rails-crud/ending-code/study-group-sushi/app/models/sushi.rb
class Sushi < ApplicationRecord
    validates :name, uniqueness: true
    validates :name, presence: true

end

Mod-3/Week-1/lecture-3-rails-crud/ending-code/study-group-sushi/app/controllers/sushis_controller.rb
class SushisController < ApplicationController
    before_action :set_sushi, only: [:show, :edit, :update, :destroy]

    def index
      @sushis = Sushi.all
    end

    def show
      if !@sushi
        redirect_to sushis_path
      end
    end

    def new
      @sushi = Sushi.new
    end

    def create
      binding.pry
      @sushi = Sushi.new(sushi_params)
      if @sushi.save
        redirect_to sushi_path(@sushi)
      else
        render "new"
      end
    end

    def edit
      if !@sushi
        redirect_to sushis_path
      end
    end

    def update
      if @sushi
        @sushi.update(sushi_params)
        if @sushi.errors.any?
          render "edit"
        else
          redirect_to @sushi
        end
      else
        render "edit"
      end
    end

    def destroy
      @sushi.destroy
      redirect_to sushis_path
    end

    private

    def set_sushi
      @sushi = Sushi.find_by_id(params[:id])
    end

    def sushi_params
      params.require(:sushi).permit(:name)
    end
end

Mod-3/Week-1/lecture-3-rails-crud/ending-code/study-group-sushi/app/views/sushis/edit.erb
<h1>
  Mix it up!
</h1>
<div class="container">
    <div class="row">
        <div class="col-xs-8">
            <p>Alter this sushi to your heart's content:</p>
            <br/>
            <%= form_with model: @sushi do |f| %>
                <%= f.text_field :name %>
                <%= f.submit %>
            <% end %>

        </div>
        <div class="col-xs-4">
            <div class="card" style="width: 20rem;">
                <img class="card-img-top img-responsive" src="https://images.bigcartel.com/product_images/198520063/BlueRose.jpg?auto=format&fit=max&h=1000&w=1000"/>
                <div class="card-block">
                    <p class="card-text">Sushi so good you won't believe it exists in nature!</p>
                </div>
            </div>
        </div>
    </div>
</div>

Mod-3/Week-1/lecture-3-rails-crud/ending-code/study-group-sushi/app/views/sushis/index.erb
<h1>Browse our Mountains of Sushi:</h1>
<div class="container">
    <div class="row">
        <div class="col-xs-6">
            <ul>
                <% @sushis.each do | sushi | %>
                    <li><%= link_to sushi.name, "/sushis/#{sushi.id}" %></li>
                    <li><%= link_to sushi.name, sushi_path(sushi) %></li>
                    <li><%= link_to sushi.name, sushi %></li>
                <% end %>
            </ul>
            <p><%= link_to "Create a new sushi", new_sushis_path %></p>

            <p><%= link_to "Google", "http://google.com" %></p>
        </div>
        <div class="col-xs-6">
            <div class="background-div">
                <img class="img-responsive fixed-image img-circle" src="https://cdn.dribbble.com/users/644992/screenshots/1772842/twin_peaks.jpg"/>
            </div>
        </div>
    </div>
</div>

Mod-3/Week-1/lecture-3-rails-crud/ending-code/study-group-sushi/app/views/sushis/new.erb
<h1>Build-your-own sushi!</h1>
<div class="container">
    <div class="row">
        <div class="col-xs-8">
            <br/>
            <p>You name it, we make it. Fill out your preference and our waiter will bring it directly to you.</p>
            <br/>
            <%# Form goes here %>
           
            <%= form_tag "/sushis" do %>
                <%= text_field_tag :name %>
                <%= submit_tag "Create Sushi" %>
            <% end %>

            <%# <%= form_for @sushi do |f| %>
                <%#= f.text_field :name %>
                <%#= f.submit %>
            <%# end %>

            <%#= form_with url: "/sushis" do |f| %>
                <%#= f.text_field :name %>
                <%#= f.submit "Create Sushi" %>
            <%# end %>

            <%#= form_with model: @sushi do |f| %>
                <%#= f.text_field :name %>
                <%#= f.submit %>
            <%# end %> 


        </div>
        <div class="col-xs-4">
            <div class="card" style="width: 20rem;">
                <img class="card-img-top img-responsive" src="https://i.pinimg.com/736x/58/b1/d7/58b1d789616aa6ef4ae6b56cf86af16b--coffee-geek-drink-coffee.jpg"/>
                <div class="card-block">
                    <p class="card-text">Every sushi order comes with a cup of damn fine coffee.</p>
                </div>
            </div>
        </div>
    </div>
</div>

Mod-3/Week-1/lecture-3-rails-crud/ending-code/study-group-sushi/app/views/sushis/show.erb
<h2>
  Every day, once a day, give yourself a present.
</h2>

<p>
  Your fresh sushi and hot coffee have arrived! Please check to make sure it is to your specifications.</p>
<div class="wrapping">
  <img class="img-responsive" src="http://sweetclipart.com/multisite/sweetclipart/files/sushi_rolls_futomaki_ebi.png"/>
</div>

<h4 class="red-text"> Name: <%= @sushi.name %> </h4>
<h6><%= link_to "Edit your sushi", edit_sushi_path(@sushi) %></h6>
<h6><%= link_to("Delete your sushi", @sushi, method: :delete, data:{confirm: "Do you really want to delete me?"}) %></h6>